#!/bin/bash
echo 'name age
alice 21
ryan 30' > file.txt

# FIXME Use shell language

# awk '
# {
#   for (i=1; i <= NF; ++i)
#     cols[i-1, NR-1] = $i
# }
# END {
#   for (i=0; i < NF; ++i) {
#     for (j=0;j < NR-1; ++j) {
#       printf("%s ", cols[i, j])
#     }
#     printf("%s", cols[i, NR-1])
#     printf("\n")
#   }
# }' file.txt

awk '
{
  for (i = 1; i <= NF; ++i) {
    if (NR == 1) {
      line[i-1] = $i
    } else {
      line[i-1] = line[i-1]" "$i
    }
  }
}
END {
  for (i = 0; i < NF; ++i) {
    print line[i]
  }
}' file.txt

rm file.txt
