#!/bin/python3
import sys

def GenCMakeLists(project_name):
    return """set(BUILD_ALL_EXAMPLES OFF CACHE BOOL "Determine if build all examples")
message(STATUS "BUILD_ALL_EXAMPLES: ${BUILD_ALL_EXAMPLES}")
macro (GenExample exec_name src_list lib_list)
  GenExec(${{exec_name}} ${{src_list}} ${{lib_list}})
endmacro ()"""

if len(sys.argv) < 3:
    print("Usage: ./gen_cmakelists.py project_name output_filename")
    exit(0)

project_name = sys.argv[1]
output_filename = sys.argv[2]
output_file = open(output_filename, "w")
output_file.write(GenCMakeLists(project_name))
output_file.close()
